const GRID_LIST_INIT = '[grid list] GRID_LIST_INIT'
const GRID_LIST_CHANGE_FLAVOUR = '[grid list] GRID_LIST_CHANGE_FLAVOUR'
const GRID_LIST_CHANGE_CHECKBOX = '[grid list] GRID_LIST_CHANGE_CHECKBOX'
const GRID_LIST_CHANGE_RADIO = '[grid list] GRID_LIST_CHANGE_RADIO'
const GRID_LIST_RESET_FLAVOUR = '[grid list] GRID_LIST_RESET_FLAVOUR'
const GRID_LIST_TOGGLE_PROFILE = '[grid list] GRID_LIST_TOGGLE_PROFILE'

export const C = {
  GRID_LIST_TOGGLE_PROFILE,
  GRID_LIST_CHANGE_RADIO,
  GRID_LIST_CHANGE_CHECKBOX,
  GRID_LIST_RESET_FLAVOUR,
  GRID_LIST_CHANGE_FLAVOUR,
  GRID_LIST_INIT,
}
