const GRID_LIST_INIT = '[grid list] GRID_LIST_INIT'
const GRID_LIST_CHANGE_FLAVOUR = '[grid list] GRID_LIST_CHANGE_FLAVOUR'
const GRID_LIST_RESET_FLAVOUR = '[grid list] GRID_LIST_RESET_FLAVOUR'

export const C = {
  GRID_LIST_RESET_FLAVOUR,
  GRID_LIST_CHANGE_FLAVOUR,
  GRID_LIST_INIT,
}
