const GRID_LIST_INIT = '[grid list] GRID_LIST_INIT'
const GRID_LIST_CHANGE_FLAVOUR = '[grid list] GRID_LIST_CHANGE_FLAVOUR'
const GRID_LIST_CHANGE_CHECKBOX = '[grid list] GRID_LIST_CHANGE_CHECKBOX'
const GRID_LIST_CHANGE_RADIO = '[grid list] GRID_LIST_CHANGE_RADIO'
const GRID_LIST_RESET_FLAVOUR = '[grid list] GRID_LIST_RESET_FLAVOUR'
const GRID_LIST_TOGGLE_PROFILE = '[grid list] GRID_LIST_TOGGLE_PROFILE'
const GRID_LIST_FORCE_SELECT_ONE = '[grid list] GRID_LIST_FORCE_SELECT_ONE'
const GRID_LIST_INCREASE_PAGE_NUMBER =
  '[grid list] GRID_LIST_INCREASE_PAGE_NUMBER'
const GRID_LIST_INCREASE_UPDATE = '[grid list] GRID_LIST_INCREASE_UPDATE'

export const C = {
  GRID_LIST_INCREASE_UPDATE,
  GRID_LIST_INCREASE_PAGE_NUMBER,
  GRID_LIST_FORCE_SELECT_ONE,
  GRID_LIST_TOGGLE_PROFILE,
  GRID_LIST_CHANGE_RADIO,
  GRID_LIST_CHANGE_CHECKBOX,
  GRID_LIST_RESET_FLAVOUR,
  GRID_LIST_CHANGE_FLAVOUR,
  GRID_LIST_INIT,
}
